routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
Route::get('/','UsersController@index');
Route::get('/dashboard','UsersController@index');

Route::get('/dashboard2','UsersController@index2');

Route::get('/checkout','UsersController@index3');

Route::get('/cart','CartController@index');
Route::get('/laptop','LaptopController@index');
Route::get('/accessories','AccessoriesController@index');
Route::get('/items','OthersController@index');


Route::get('/detail','LaptopController@index');
Auth::routes();

Route::get('/logout','Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

//product
Route::get('/product','ProductsController@create');


Route::post('/addresstore','AdressesController@store')->name('adress.store');



Route::group(['prefix'=>'admin','middleware'=>'auth'], function(){

    Route::get('/', function () {

        return view('Users.admin.index');
        
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');

});

Route::resource('address', 'AdressesController');


/* cart route */
Route::resource('cart', 'CartController');

/* payment route */

Route::post('store-payment','UsersController@store')->name('payment.store');

resources/views/Users/admin/layout/includes/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="{{route('admin.index')}}">Admin</a></h1>
                </div>
            </div>

            <div class="col-md-2 pull-right">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="{{url('#')}}" class="dropdown-toggle" data-toggle="dropdown">{{auth :: user()->name}} <b
                                            class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <li><a href="{{url('/')}}">Front End</a></li>
                                    <li><a href="{{url('/logout')}}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/Users/admin/layout/includes/sidenav.blade.php
{{-- Side Navigation --}}
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block;">
        <ul class="nav">
            <!-- Main menu -->
            <li class="current"><a href="{{route('admin.index')}}"><i class="glyphicon glyphicon-home"></i>
                    Dashboard</a></li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Products
                    <span class="caret pull-right"></span>
                </a>
                <!-- Sub menu -->
                <ul>
                    <li><a href="{{route('product.create')}}">Add Product</a></li>
                </ul>
                <ul>
                        <li><a href="{{route('product.index')}}">View Product</a></li>
                    </ul>
                    <li class="submenu">
                            <a href="#">
                                <i class="glyphicon glyphicon-list"></i> Category
                                <span class="caret pull-right"></span>
                            </a>
                            <!-- Sub menu -->
                            <ul>
                                <li><a href="{{route('category.index')}}">Categories</a></li>
                            </ul>
                            
            </li>
        </ul>
    </div>
</div> <!-- ADMIN SIDE NAV-->